### ISSUE TITLE
Packer 1.4.5 builds now fail - semantics of ami_regions changed?

### ISSUE THREAD

**Issue by felddy** [cisagov/skeleton-packer#22]
# 🐛 Bug Report

Packer v1.4.5 seemingly has changed the semantics of some of the packer configuration values.  It also now requires `encrypt_boot` to be set explicitly.  

The error seems to be that `ami_regions` is now explicitly trying to copy the AMI, even if it is the same as the build `region`.  Previously this was not the case.  See "successful build" below. 

https://www.packer.io/docs/builders/amazon-ebs.html

See:
- https://github.com/hashicorp/packer/pull/8288
- https://github.com/hashicorp/packer/issues/8271
- https://github.com/hashicorp/packer/issues/8204
- https://github.com/hashicorp/packer/issues/8299
 
## To Reproduce

- Create a pre-release

## Expected behavior

Successfully deploying pre-releases builds to one region, and release builds to multiple.

## Any helpful log output

Successful build:
https://github.com/cisagov/skeleton-packer/commit/6a01198b790a97aef8b15deb99c4ae0f5e0659e1/checks?check_suite_id=280523117#step:10:136

Error build: 
https://github.com/cisagov/skeleton-packer/commit/5e614ad44ceed953e38f299ec1e3ab9fa1fb3919/checks?check_suite_id=297319322#step:13:140

**Comment by felddy** [comment]
Here is what the build looks like once the patcher is run:

```bash
    AWS_DEFAULT_REGION: us-east-2
    BUILD_REGION: us-east-2
    CURL_CACHE_DIR: $HOME/.cache/curl
    DEPLOY_REGION_KMS_MAP: us-east-2:alias/cool/ebs
    PACKER_VERSION: 1.4.5
    TERRAFORM_VERSION: 0.12.13
    pythonLocation: /opt/hostedtoolcache/Python/3.7.5/x64
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    GITHUB_IS_PRERELEASE: true
    GITHUB_RELEASE_TAG: v0.0.6
    GITHUB_RELEASE_URL: https://github.com/cisagov/skeleton-packer/releases/tag/v0.0.6
```

```yaml
{
  "builders": [
    {
      "ami_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/xvda",
          "encrypted": true,
          "volume_size": 8,
          "volume_type": "gp2"
        }
      ],
      "ami_name": "example-hvm-{{timestamp}}-x86_64-ebs",
      "ami_regions": "us-east-2",
      "encrypt_boot": true,
      "instance_type": "t3.small",
      "launch_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/xvda",
          "encrypted": true,
          "volume_size": 8,
          "volume_type": "gp2"
        }
      ],
      "region": "{{user `build_region`}}",
      "region_kms_key_ids": {
        "us-east-2": "alias/cool/ebs"
      },
      "source_ami_filter": {
        "filters": {
          "name": "debian-10-amd64-*",
          "root-device-type": "ebs",
          "virtualization-type": "hvm"
        },
        "most_recent": true,
        "owners": [
          "136693071363"
        ]
      },
      "ssh_username": "admin",
      "tags": {
        "Application": "Example",
        "Base_AMI_Name": "{{ .SourceAMIName }}",
        "GitHub_Release_URL": "{{user `github_release_url`}}",
        "OS_Version": "Debian Buster",
        "Pre_Release": "{{user `github_is_prerelease`}}",
        "Release": "{{user `github_release_tag`}}",
        "Team": "CISA - Development"
      },
      "type": "amazon-ebs"
    }
  ],
  "provisioners": [
    {
      "groups": [
        "aws",
        "example"
      ],
      "playbook_file": "src/playbook.yml",
      "type": "ansible"
    },
    {
      "execute_command": "chmod +x {{ .Path }}; sudo env {{ .Vars }} {{ .Path }} ; rm -f {{ .Path }}",
      "inline": [
        "sed -i '/^users:/ {N; s/users:.*/users: []/g}' /etc/cloud/cloud.cfg",
        "rm --force /etc/sudoers.d/90-cloud-init-users",
        "rm --force /root/.ssh/authorized_keys",
        "/usr/sbin/userdel --remove --force admin"
      ],
      "skip_clean": true,
      "type": "shell"
    }
  ],
  "sensitive-variables": [],
  "variables": {
    "build_region": "{{env `BUILD_REGION`}}",
    "github_is_prerelease": "{{env `GITHUB_IS_PRERELEASE`}}",
    "github_release_tag": "{{env `GITHUB_RELEASE_TAG`}}",
    "github_release_url": "{{env `GITHUB_RELEASE_URL`}}"
  }
}
```
